# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: vpn-seed-server-keys
  namespace: shoot-<shoot name an project>
type: Opaque
data:
  ca-crt.pem: << base64 >>
  server-key.pem: << base64 >>
  server-cert.pem: << base64 >>
  vpn.tlsauth: << base64 >>
  dh2048.pem: << base64 >>
