# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpn-seed-server
  namespace: shoot-<shoot name an project>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpn-seed-server
  template:
    metadata:
      labels:
        app: vpn-seed-server
    spec:
      priorityClassName: system-cluster-critical
      tolerations:
      - effect: NoExecute
        operator: Exists
      containers:
      - name: vpn-seed-server
        image: europe-docker.pkg.dev/gardener-project/public/gardener/vpn-seed-server:0.9.0
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
        resources:
          requests:
            cpu: 100m
        volumeMounts:
        - name: vpn-secrets
          mountPath: /srv/secrets
        env:
        - name: SERVICE_NETWORK
          value: # service network, e.g. 100.68.0.0/14
        - name: POD_NETWORK
          value: # pod network, e.g. 100.96.0.0/16
        - name: NODE_NETWORK
          value: # node network, e.g. 10.250.0.0/16
        - name: VPN_NETWORK
          value: # VPN network, e.g. 192.168.123.0/24
      volumes:
      - name: vpn-secrets
        secret:
          defaultMode: 0400
          secretName: vpn-seed-server-keys
