# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: Service
metadata:
  name: vpn-seed-service
  namespace: shoot-<shoot name an project>
spec:
  selector:
    app: vpn-seed-server
  type: LoadBalancer
  ports:
  - name: openvpn
    protocol: TCP
    port: 1194
    targetPort: 1194
