# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: vpn-shoot-client-keys
  namespace: kube-system
type: Opaque
data:
  ca-crt.pem: << base64 >>
  client-key.pem: << base64 >>
  client-cert.pem: << base64 >>
  vpn.tlsauth: << base64 >>
